---
driver:
  name: docker
  hostname: ntp.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false



provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: ntp
  log_level: info
  state_top:
    base:
      "*":
        - ntp
  pillars:
    top.sls:
      base:
        "*":
          - ntp
  grains:
    noservices: True


platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1


verifier:
  name: inspec
  sudo: true


suites:

  - name: client
    provisioner:
      pillars-from-files:
        ntp.sls: tests/pillar/client.sls

  - name: server
    provisioner:
      pillars-from-files:
        ntp.sls: tests/pillar/server.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
